### ISSUE TITLE
Noção espacial para o usuário

### ISSUE THREAD

**Issue by 7robertodantas** [MeFormei/camera#1]
- Ajustar telinha do OpenCV (mostrar apenas desenho dos limites e posição atual no opencv, sem visualização da imagem real)
- Realizar testes de cursor na página web (sem prejudicar desempenho)

**Comment by 7robertodantas** [comment]
@PCoelho07 @lucascriistiano

**Comment by lucascriistiano** [comment]
Tem que se pensar se isso vai ser feito no OpenCV ou como um elemento da página já no cliente (no navegador), porque a escolha de cada um tem seus benefícios e prejuízos. 
No OpenCV, por exemplo, ganharíamos na facilidade para implementar a exibição (porque já tá praticamente feito).
Por outro lado, teríamos que manter a renderização de duas janelas (duas janelas abertas, possivelmente podendo perder o foco e esconder a telinha menor) e acredito que ocuparia mais memória para manter a renderização nesses dois processos gráficos, além de estar inserindo um gargalo no processamento da posição, podendo diminuir a fluidez pra determinar a posição atual pelo OpenCV se esse também tiver de renderizar na telinha a posição do controle.

**Comment by PCoelho07** [comment]
Se esse gargalo for realmente significativo, acho que deveria ser feito no browser, vai dar mais ou pouco de trabalho "braçal" do que se fosse feito direto no OpenCv, mas deixaria o RPi menos sobrecarregado. Agora, só se esse gargalo fosse realmente comprometer algo.

**Comment by lucascriistiano** [comment]
Não sei também como "fixar" a janela menor sempre sendo sempre exibida (se ela não for um componente da página), uma vez que sempre seria necessário que ela fosse exibida sobre a visualização da página do browser. Uma vez que ela podia perder o foco em relação ao browser, poderia ser escondida pelo navegador, e mesmo sendo renderizada pelo OpenCV não seria visualizada pelo usuário.

**Comment by 7robertodantas** [comment]
Eu também prefiro a ideia da view ficar em um lugar só. Deixando a renderização em uma janela a parte fica dificil de ajustar e garantir que ambas estejam aparecendo.

Dica: Talvez com Canvas HTML seja possível desenhar na tela os limites e a posição da "bola". E também, usando CSS seja possível definir o z-index para colocar a tag de canvas na frente de tudo.

@PCoelho07 @lucascriistiano

**Comment by lucascriistiano** [comment]
Perfeito. Podemos combinar assim e definir uma nova issue para reinserir no código atual a integração com o front end para envio das coordenadas e posterior renderização. Todos de acordo?

@7robertodantas  @PCoelho07

**Comment by PCoelho07** [comment]
Sim, concordo plenamente @lucascriistiano
